---
name: Build

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "3 4 * * 0"

jobs:
  # Test the build environment.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test building the build environment.
        run: docker compose up -d
